### ISSUE TITLE
Potential security issue in src/idl_parser.cpp: Unchecked return from initialization function

### ISSUE THREAD

**Issue by monocle-ai** [sagpant/flatbuffers#1]
<span> What is a&nbsp;</span><span><b>Conditionally Uninitialized Variable? </b></span><span> The return value of a function that is potentially used to initialize a local variable is not checked. Therefore, reading the local variable may result in undefined behavior.</span>
---

2 instances of this defect were found in the following locations:
---
**Instance 1**
File : `src/idl_parser.cpp` 
Function: `$StringToNumber@N@flatbuffers` 
https://github.com/sagpant/flatbuffers/blob/cc44a4442716601600aa50fb8a42abd55294212c/src/idl_parser.cpp#L2809
Code extract:

```cpp
      break;
    case kTokenFloatConstant: {
      double d;
      StringToNumber(attribute_.c_str(), &d); <------ HERE
      builder->Double(d);
      EXPECT(kTokenFloatConstant);
```

**How can I fix it?** 
Correct reference usage found in `src/code_generators.cpp` at line `186`.
https://github.com/sagpant/flatbuffers/blob/cc44a4442716601600aa50fb8a42abd55294212c/src/code_generators.cpp#L186
Code extract:

```cpp
    const FieldDef &field) const {
  const auto &constant = field.value.constant;
  T v;
  auto done = StringToNumber(constant.c_str(), &v); <------ HERE
  FLATBUFFERS_ASSERT(done);
  if (done) {
```

---
**Instance 2**
File : `src/idl_parser.cpp` 
Function: `$StringToNumber@N@flatbuffers` 
https://github.com/sagpant/flatbuffers/blob/cc44a4442716601600aa50fb8a42abd55294212c/src/idl_parser.cpp#L3267
Code extract:

```cpp
                    ? builder->CreateVectorOfStrings(doc_comment)
                    : 0;
  double d;
  StringToNumber(value.constant.c_str(), &d); <------ HERE
  return reflection::CreateField(
      *builder, name__, type__, id, value.offset,
```

**How can I fix it?** 
Correct reference usage found in `src/code_generators.cpp` at line `186`.
https://github.com/sagpant/flatbuffers/blob/cc44a4442716601600aa50fb8a42abd55294212c/src/code_generators.cpp#L186
Code extract:

```cpp
    const FieldDef &field) const {
  const auto &constant = field.value.constant;
  T v;
  auto done = StringToNumber(constant.c_str(), &v); <------ HERE
  FLATBUFFERS_ASSERT(done);
  if (done) {
```

**Comment by siva-msft** [comment]
lgtm
